/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SazonalidadeRouteImport } from './routes/sazonalidade'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as FamiliasRouteImport } from './routes/familias'
import { Route as ExportarRouteImport } from './routes/exportar'
import { Route as ComparativosRouteImport } from './routes/comparativos'
import { Route as IndexRouteImport } from './routes/index'

const SazonalidadeRoute = SazonalidadeRouteImport.update({
  id: '/sazonalidade',
  path: '/sazonalidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliasRoute = FamiliasRouteImport.update({
  id: '/familias',
  path: '/familias',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportarRoute = ExportarRouteImport.update({
  id: '/exportar',
  path: '/exportar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparativosRoute = ComparativosRouteImport.update({
  id: '/comparativos',
  path: '/comparativos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comparativos': typeof ComparativosRoute
  '/exportar': typeof ExportarRoute
  '/familias': typeof FamiliasRoute
  '/forecast': typeof ForecastRoute
  '/insights': typeof InsightsRoute
  '/produtos': typeof ProdutosRoute
  '/sazonalidade': typeof SazonalidadeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comparativos': typeof ComparativosRoute
  '/exportar': typeof ExportarRoute
  '/familias': typeof FamiliasRoute
  '/forecast': typeof ForecastRoute
  '/insights': typeof InsightsRoute
  '/produtos': typeof ProdutosRoute
  '/sazonalidade': typeof SazonalidadeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comparativos': typeof ComparativosRoute
  '/exportar': typeof ExportarRoute
  '/familias': typeof FamiliasRoute
  '/forecast': typeof ForecastRoute
  '/insights': typeof InsightsRoute
  '/produtos': typeof ProdutosRoute
  '/sazonalidade': typeof SazonalidadeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comparativos'
    | '/exportar'
    | '/familias'
    | '/forecast'
    | '/insights'
    | '/produtos'
    | '/sazonalidade'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/comparativos'
    | '/exportar'
    | '/familias'
    | '/forecast'
    | '/insights'
    | '/produtos'
    | '/sazonalidade'
  id:
    | '__root__'
    | '/'
    | '/comparativos'
    | '/exportar'
    | '/familias'
    | '/forecast'
    | '/insights'
    | '/produtos'
    | '/sazonalidade'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComparativosRoute: typeof ComparativosRoute
  ExportarRoute: typeof ExportarRoute
  FamiliasRoute: typeof FamiliasRoute
  ForecastRoute: typeof ForecastRoute
  InsightsRoute: typeof InsightsRoute
  ProdutosRoute: typeof ProdutosRoute
  SazonalidadeRoute: typeof SazonalidadeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sazonalidade': {
      id: '/sazonalidade'
      path: '/sazonalidade'
      fullPath: '/sazonalidade'
      preLoaderRoute: typeof SazonalidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/familias': {
      id: '/familias'
      path: '/familias'
      fullPath: '/familias'
      preLoaderRoute: typeof FamiliasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exportar': {
      id: '/exportar'
      path: '/exportar'
      fullPath: '/exportar'
      preLoaderRoute: typeof ExportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparativos': {
      id: '/comparativos'
      path: '/comparativos'
      fullPath: '/comparativos'
      preLoaderRoute: typeof ComparativosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComparativosRoute: ComparativosRoute,
  ExportarRoute: ExportarRoute,
  FamiliasRoute: FamiliasRoute,
  ForecastRoute: ForecastRoute,
  InsightsRoute: InsightsRoute,
  ProdutosRoute: ProdutosRoute,
  SazonalidadeRoute: SazonalidadeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
